### PR TITLE
Added Symfony 3 to composer requirements

### PR DESCRIPTION
**Pull request by mwansinck**

### CODE REVIEW

**Comment by Padam87** [comment]
Thank you for the PR. Unfortunately I cannot merge it like this. The framework bundle is not required by this bundle, therefore doing an insanceof check is no good. Please revert that commit.

**Comment by Padam87** [comment]
Oh, and please use `~3.0` instead of `~3`.

**Comment by mwansinck** [comment]
~3 has been changed to ~3.0.

However, you where already comparing the class of the Command file with Symfony\Bundle\FrameworkBundle\Console\Application in your code;

see: [(https://github.com/adiuvonl/CronBundle/commit/859378964644548e7ddc554b84358ebcd004d6b7)]

Thereby your Bundle was already depending on Symfony\Bundle\FrameworkBundle\Console\Application. I only made the check less restrictive because some bundles (like [jms-job-queue bundle](https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Console/Application.php)) are extending the Symfony\Bundle\FrameworkBundle\Console\Application.

Semantically your composer bundle should contain a dependency for Symfony\Bundle\FrameworkBundle\Console\Application because your bundle wouldn't work without it...

If you don't agree, alternatively I can suggest to add the  JMS\JobQueueBundle\Console\Application to the get_class check like this;

```
if (get_class($this->getApplication()) == 'Symfony\Bundle\FrameworkBundle\Console\Application' || get_class($this->getApplication()) == 'JMS\JobQueueBundle\Console\Application') {
    /** @noinspection PhpUndefinedMethodInspection */
    /** @var ContainerInterface $container */
    $container = $this->getApplication()->getKernel()->getContainer();
    $config = $container->getParameter('padam87_cron');
} else {
    throw new \Exception('Not implemented yet. PRs are welcome, as always.');
}
```

I am happy to create a PR for both, but personally I would prefer the first solution.

**Comment by Padam87** [comment]
This is exactly the point of this implementation... this only compares a string, no need for a dependency. Revert pls

If you really need the JMS bundle compatibility, it could be replaced with a method_exists call.

**Comment by mwansinck** [comment]
Yes, I really need JMS bundle compatibility, so I implemented the method_exists call

**Pull request merged**
