### PR TITLE
Added config option php_binary

### PR DESCRIPTION
**Pull request by mwansinck**
Added config option to set the path of the php binary put in the generated crontab. 
We needed this to run the cron from a different container than where the crontab is generated from.

```
padam87_cron:
  php_binary: docker exec <container_name> php ....
```

### CODE REVIEW

**Comment by Padam87** [comment]
I'd prefer setting the default value in the config, `null` doesn't really make sense here.

The `log_dir` is different, if it is set to null, it is not used.

**Comment by mwansinck** [comment]
You are right, a default value in the config makes sense. I will update the PR on monday.

**Comment by mwansinck** [comment]
PR has been updated

**Comment by Padam87** [comment]
Merged and released. Thank you @mwansinck !

**Pull request merged**
